# Generated by Django 5.0.7 on 2025-09-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_listing_idx_listing_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at'], 'permissions': (('can_approve_listings', 'Can approve or reject listings'), ('can_view_analytics', 'Can view marketplace analytics'), ('can_manage_categories', 'Can manage marketplace categories'), ('can_manage_transactions', 'Can manage marketplace transactions'))},
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('active', 'Active'), ('sold', 'Sold'), ('archived', 'Archived')], db_index=True, default='pending', max_length=16),
        ),
    ]
