# Generated by Django 5.0.7 on 2025-09-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_transaction_status_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='action',
            field=models.CharField(choices=[('buyer_request', 'Buyer Request'), ('seller_accept', 'Seller Accepted'), ('seller_reject', 'Seller Rejected'), ('seller_negotiate', 'Seller Negotiated'), ('offer_submitted', 'Offer Submitted'), ('offer_countered', 'Offer Countered'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected'), ('meetup_proposed', 'Meetup Proposed'), ('meetup_updated', 'Meetup Updated'), ('meetup_confirmed', 'Meetup Confirmed'), ('mod_approve_listing', 'Moderator Approved Listing'), ('mod_reject_listing', 'Moderator Rejected Listing'), ('request_completed', 'Request Completed'), ('request_canceled', 'Request Canceled')], db_index=True, max_length=40),
        ),
    ]
