# Generated by Django 5.0.7 on 2025-10-01 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_add_meetup_timezone_and_reschedule_reason'),
        ('marketplace', '0011_seed_default_categories'),
    ]

    operations = [
    ]
