# Generated by Django 5.0.7 on 2025-10-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_merge_20251002_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('request_created', 'Request Created'), ('status_changed', 'Status Changed'), ('message_posted', 'Message Posted'), ('system_broadcast', 'System Broadcast')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='meetup_timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reschedule_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='action',
            field=models.CharField(choices=[('buyer_request', 'Buyer Request'), ('seller_accept', 'Seller Accepted'), ('seller_reject', 'Seller Rejected'), ('seller_negotiate', 'Seller Negotiated'), ('offer_submitted', 'Offer Submitted'), ('offer_countered', 'Offer Countered'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected'), ('meetup_proposed', 'Meetup Proposed'), ('meetup_updated', 'Meetup Updated'), ('meetup_confirmed', 'Meetup Confirmed'), ('dispute_opened', 'Dispute Opened'), ('dispute_resolved', 'Dispute Resolved'), ('mod_approve_listing', 'Moderator Approved Listing'), ('mod_reject_listing', 'Moderator Rejected Listing'), ('request_completed', 'Request Completed'), ('request_canceled', 'Request Canceled')], db_index=True, max_length=40),
        ),
    ]
