# Generated by Django 5.0.7 on 2025-10-03 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_create_marketplace_admin_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'permissions': [('can_broadcast_notifications', 'Can broadcast notifications')]},
        ),
        migrations.AddField(
            model_name='listing',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='rejected_reason_code',
            field=models.CharField(blank=True, choices=[('spam', 'Spam or Promotional Content'), ('prohibited_item', 'Prohibited or Unsafe Item'), ('missing_info', 'Missing Required Information'), ('inappropriate_content', 'Inappropriate Content'), ('fake_photos', 'Misleading or Stock Photos'), ('pricing_issue', 'Unreasonable Pricing'), ('other', 'Other')], max_length=32),
        ),
    ]
