# Generated by Django 5.0.7 on 2025-10-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_alter_notification_options_listing_rejected_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_listing', 'Can approve/reject listings'), ('can_view_analytics', 'Can view analytics')]},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'permissions': [('can_moderate_reports', 'Can handle user reports')]},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'permissions': [('can_manage_transactions', 'Can manage marketplace transactions')]},
        ),
    ]
