# Generated by Django 4.2.25 on 2025-10-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_normalize_listing_status_and_reason_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('closed', 'Closed')], db_index=True, default='open', max_length=10),
        ),
    ]
