# Generated by Django 4.2.25 on 2025-11-05 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0018_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='meetup_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('showed_up', 'Showed Up'), ('no_show_buyer', 'No-show (Buyer)'), ('no_show_seller', 'No-show (Seller)')], db_index=True, default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='no_show_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='no_show_reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_no_shows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TransactionDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispute_type', models.CharField(choices=[('item_not_as_described', 'Item Not as Described'), ('no_show', 'No-show'), ('payment_issue', 'Payment Issue'), ('other', 'Other')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('evidence_photos', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='under_review', max_length=20)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_disputes', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='marketplace.purchaserequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('is_admin', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_messages', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.transactiondispute')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/')),
                ('trust_score', models.PositiveIntegerField(default=100)),
                ('verified', models.BooleanField(default=False)),
                ('no_show_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'indexes': [models.Index(fields=['user'], name='idx_mkt_profile_user'), models.Index(fields=['verified'], name='idx_mkt_profile_verified')],
            },
        ),
        migrations.AddIndex(
            model_name='transactiondispute',
            index=models.Index(fields=['transaction', 'status'], name='idx_dispute_tx_status'),
        ),
        migrations.AddIndex(
            model_name='transactiondispute',
            index=models.Index(fields=['reporter'], name='idx_dispute_reporter'),
        ),
        migrations.AddIndex(
            model_name='disputemessage',
            index=models.Index(fields=['dispute', 'created_at'], name='idx_disputemsg_dispute_created'),
        ),
        migrations.AddIndex(
            model_name='disputemessage',
            index=models.Index(fields=['author'], name='idx_disputemsg_author'),
        ),
    ]
