# Generated by Django 4.2.25 on 2025-11-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_purchaserequest_meetup_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='marketplace.messagethread'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='marketplace.messagethread'),
        ),
    ]
