# Generated by Django 5.2.8 on 2025-12-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_listing_purchase_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash on Delivery'), ('gcash', 'GCash')], max_length=20, null=True),
        ),
    ]
