# Generated by Django 5.2.8 on 2026-03-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_proof_image',
            field=models.FileField(blank=True, null=True, upload_to='payments/images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('awaiting_payment', 'Awaiting Payment'), ('proof_submitted', 'Proof Submitted'), ('proof_rejected', 'Proof Rejected'), ('paid', 'Paid'), ('pending_cod', 'Pending (COD)')], db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('confirmed', 'Confirmed'), ('awaiting_payment', 'Awaiting Payment'), ('to_ship', 'To Ship'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='proposed', max_length=20),
        ),
    ]
