# Generated by Django 5.2.8 on 2026-03-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_transaction_payment_proof_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_proof_image',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('confirmed', 'Confirmed'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='proposed', max_length=20),
        ),
    ]
