# Generated by Django 5.2.8 on 2026-03-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_remove_transaction_payment_proof_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cod_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cod_contact',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cod_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cod_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gcash_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
