# Generated by Django 5.2.8 on 2026-03-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_transaction_cod_address_transaction_cod_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('proposed', 'Proposed'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], db_index=True, default='proposed', max_length=20),
        ),
    ]
