# Generated by Django 5.2.8 on 2026-03-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('confirmed', 'Confirmed'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='proposed', max_length=20),
        ),
    ]
