# Generated by Django 5.2.8 on 2026-03-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('cancelled', 'Cancelled')], db_index=True, default='proposed', max_length=20),
        ),
    ]
