# Generated by Django 5.2.8 on 2026-04-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='gcash_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='listing',
            name='gcash_qr',
            field=models.ImageField(blank=True, null=True, upload_to='listings/gcash/%Y/%m/'),
        ),
    ]
