# Generated by Django 5.2.8 on 2026-05-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_listing_gcash_name_listing_gcash_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('request_created', 'Request Created'), ('status_changed', 'Status Changed'), ('message_posted', 'Message Posted'), ('system_broadcast', 'System Broadcast'), ('security_alert', 'Security Alert')], db_index=True, max_length=32),
        ),
    ]
