# Generated by Django 5.2.8 on 2026-05-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0030_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('request_created', 'Request Created'), ('status_changed', 'Status Changed'), ('message_posted', 'Message Posted'), ('system_broadcast', 'System Broadcast')], db_index=True, max_length=32),
        ),
    ]
