# Generated by Django 5.2.5 on 2025-09-22 21:25

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pendingcommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingschedule',
            name='days_of_week',
            field=models.JSONField(default=app.models.default_days_of_week),
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='label',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedingschedule',
            name='portion_size',
            field=models.FloatField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
