# Generated by Django 5.2.5 on 2025-09-27 13:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    # This migration is intentionally left as a no-op because the custom User
    # model is now created in 0001_initial to satisfy swappable dependencies.
    # Keeping this file avoids breaking existing databases where 0002 was applied.
    operations = []
