# Generated by Django 5.0.7 on 2025-09-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_preferred_language_remove_user_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_marketplace_notifications',
            field=models.BooleanField(default=True, help_text='Receive marketplace-related emails (requests, status changes, messages)'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_on_messages',
            field=models.BooleanField(default=True, help_text='Receive emails when new messages are posted on a request'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_on_request_updates',
            field=models.BooleanField(default=True, help_text='Receive emails for request-created/accepted/rejected/negotiated/meetup/complete/cancel'),
        ),
    ]
