# Generated by Django 5.0.7 on 2025-10-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_marketplace_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_marketplace_notifications',
            field=models.BooleanField(default=True, help_text='Show marketplace notifications in the notifications page'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_on_messages',
            field=models.BooleanField(default=True, help_text='Show notifications when new messages are posted on a request'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_on_request_updates',
            field=models.BooleanField(default=True, help_text='Show notifications for request-created/accepted/rejected/meetup/complete/cancel'),
        ),
    ]
