# Generated by Django 5.2.5 on 2025-09-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_feedingschedule_days_of_week_feedingschedule_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('wifi_rssi', models.IntegerField(blank=True, null=True)),
                ('uptime', models.IntegerField(blank=True, null=True)),
                ('daily_feeds', models.IntegerField(default=0)),
                ('last_feed', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
