# Generated by Django 5.2.6 on 2025-11-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_device_scoping_and_events'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commandevent',
            new_name='controller__command_f8ced3_idx',
            old_name='commandevent_cmd_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingcommand',
            new_name='controller__status_23cd4f_idx',
            old_name='pendingcommand_status_created_idx',
        ),
        migrations.AlterField(
            model_name='commandevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
