# Generated by Django 4.2.25 on 2025-12-11 15:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controller', '0006_rename_commandevent_cmd_status_created_idx_controller__command_f8ced3_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], db_index=True, max_length=8)),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('ideal_weight_min_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5)])),
                ('ideal_weight_max_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5)])),
            ],
            options={
                'ordering': ['species', 'name'],
                'unique_together': {('species', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=8)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age_years', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pet_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='controller.petbreed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PetMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('bcs', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('measurement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='controller.pet')),
            ],
            options={
                'ordering': ['-measurement_date', '-created_at'],
                'indexes': [models.Index(fields=['pet', 'measurement_date'], name='controller__pet_id_f2432e_idx')],
            },
        ),
    ]
