# Generated by Django 5.2.8 on 2025-12-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_petbreed_pet_petmeasurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='petmeasurement',
            name='pet',
        ),
        migrations.DeleteModel(
            name='PetBreed',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='PetMeasurement',
        ),
    ]
