# Generated by Django 5.2.8 on 2026-01-09 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_remove_pet_breed_remove_pet_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingschedule',
            name='portion_size',
            field=models.FloatField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='portion_size',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
