# Generated by Django 5.2.8 on 2026-02-14 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_hardware_controllersettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='paired_user',
        ),
        migrations.DeleteModel(
            name='ControllerSettings',
        ),
        migrations.DeleteModel(
            name='Hardware',
        ),
    ]
