# Generated by Django 5.2.8 on 2026-02-14 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0011_remove_hardware_paired_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_paired', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paired_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControllerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeding_schedule', models.JSONField(blank=True, default=dict)),
                ('portion_size', models.FloatField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hardware', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controllersettings', to='controller.hardware')),
            ],
        ),
        migrations.AddIndex(
            model_name='hardware',
            index=models.Index(fields=['unique_key'], name='idx_hardware_unique_key'),
        ),
        migrations.AddIndex(
            model_name='hardware',
            index=models.Index(fields=['is_paired'], name='idx_hardware_is_paired'),
        ),
        migrations.AddIndex(
            model_name='controllersettings',
            index=models.Index(fields=['hardware'], name='idx_settings_hardware'),
        ),
    ]
