# Generated by Django 5.2.8 on 2026-03-08 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0014_recreate_hardware_and_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='api_key_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='hardware',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PairingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(db_index=True, max_length=6)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('claimed', models.BooleanField(db_index=True, default=False)),
                ('provision_key', models.CharField(blank=True, max_length=128, null=True)),
                ('served', models.BooleanField(db_index=True, default=False)),
                ('attempts_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_sessions', to='controller.hardware')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pin', 'expires_at'], name='controller__pin_55793a_idx'), models.Index(fields=['claimed', 'served'], name='controller__claimed_b9ae46_idx')],
            },
        ),
    ]
