# Generated by Django 5.2.8 on 2026-03-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0015_hardware_api_key_hash_hardware_device_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='api_key_hash',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='device_id',
        ),
        migrations.DeleteModel(
            name='PairingSession',
        ),
    ]
