# Generated by Django 5.2.8 on 2026-03-21 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0017_hardware_api_key_hash_hardware_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingschedule',
            name='portion_size',
            field=models.FloatField(default=30, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='portion_size',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(240)]),
        ),
    ]
