# Generated by Django 5.2.8 on 2026-03-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_remove_feedinglog_timestamp_auto_now_add'),
        ('controller', '0017_hardware_api_key_hash_hardware_device_id_and_more'),
    ]

    operations = [
    ]
