# Generated by Django 5.2.8 on 2026-05-27 03:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0018_update_portion_size_wheel_30g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingschedule',
            name='portion_size',
            field=models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(160)]),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='portion_size',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(160)]),
        ),
    ]
