# Generated by Django 5.2.8 on 2025-11-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_comment_hidden_at_comment_is_flagged_post_hidden_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationaction',
            name='action_type',
            field=models.CharField(choices=[('delete_post', 'Delete Post'), ('delete_comment', 'Delete Comment'), ('restore_post', 'Restore Post'), ('restore_comment', 'Restore Comment'), ('hide_post', 'Hide Post'), ('hide_comment', 'Hide Comment'), ('warn', 'Warn'), ('suspend', 'Suspend'), ('ban', 'Ban'), ('unsuspend', 'Unsuspend'), ('resolve_report', 'Resolve Report'), ('dismiss_report', 'Dismiss Report'), ('note', 'Note')], max_length=30),
        ),
    ]
