# Generated by Django 5.2.7 on 2025-11-30 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_postdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='social/posts/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='social.post')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='PostDraft',
        ),
    ]
