# Generated by Django 5.2.8 on 2026-01-14 11:27

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_post_image_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvideo',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='social/posts/videos/'),
        ),
    ]
